"""Auto-generated column mappings."""

# This file is auto-generated by scripts/auto_map_fields.py
# Update manually if needed

COLUMN_MAPPINGS = {
    "store_id": "store_id",
    "sku_id": "product_id",
    "date_col": "dt",
    "sales_col": "sale_amount",
    "category_col": "first_category_id",
    "stockout_col": "stock_hour6_22_cnt",
    "weather_col": "avg_temperature",
    "promo_col": "discount",
}
